### PR TITLE
openpaas-gatling#15: Updated test scenarios for Calendar

### PR DESCRIPTION
**Pull request by huy-ta**
Resolves https://github.com/OpenPaaS-Suite/openpaas-gatling/issues/15.

Migrated from https://ci.linagora.com/linagora/lgs/openpaas/gatling-openpaas/merge_requests/18.

### CODE REVIEW

**Review by remk — CHANGES_REQUESTED** [review]
I don't agree on the removal of those tests.
Which make the OpenPaasMix simulation not representative at all of the workload.

They are updated and works with the PR https://github.com/OpenPaaS-Suite/openpaas-gatling/pull/14

You should rebase on it instead.

**Comment by huy-ta** [comment]
> I don't agree on the removal of those tests.
> Which make the OpenPaasMix simulation not representative at all of the workload.
> 
> They are updated and works with the PR #14
> 
> You should rebase on it instead.

The commit will be gone once the PR for Inbox has been merged and I rebase. Right now I need it so that I can run the tests.

**Comment by rouazana** [comment]
is it still a draft? should it be rebased?

**Comment by huy-ta** [comment]
Closed in favour of https://github.com/OpenPaaS-Suite/openpaas-gatling/pull/25.

**Pull request closed without merging**
